/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "ClassRatioEstimator.hpp"
#include "Kernel.hpp"
#include "QuadProg.hpp"
#include "Stopwatch.hpp"
#include "Data.hpp"
#include "Utils.hpp"
#include <vector>
#include <cfloat>
#include <armadillo>

static const float kCorrelationThreshold = 0.8;

float ClassRatioEstimator::BandwidthSelect(const Matrix& inMatrix) const
{
	int nsamples = inMatrix.Rows();
	int dimensions = inMatrix.Columns();

	float sigma = 0;
	if ( nsamples < 500 )
		sigma = 0.4 * sqrt(dimensions);
	else if ( nsamples < 1000 )
		sigma = 0.2 * sqrt(dimensions);
	else
		sigma = 0.14 * sqrt(dimensions);

	float mean_std_x = 0;
	if ( dimensions > 1E4 )
	{
		int_array colinds;
		for ( int i = 0; i < dimensions; i+=10 )
			colinds.push_back(i);

		mean_std_x = Mean(StandardDeviation(inMatrix, colinds));
	}
	else
	{
		mean_std_x = Mean(StandardDeviation(inMatrix));
	}

	return mean_std_x * sigma;
}

void ClassRatioEstimator::BestKernel(const Data& inTrain, const Data &inEval, real_array& outWeights)
{
	const Matrix &train = inTrain.Features();
	const Matrix &eval = inEval.Features();

	if ( train.Columns() != eval.Columns() )
		throw std::runtime_error("feature column count disagreement");

	const Matrix &yte = inEval.Labels();
	real_array yte_props = ClassProportions(yte);

	int noClasses = inTrain.MaxLabel();

	int dims = train.Columns();
	int n1 = train.Rows(), n2 = eval.Rows();

	float bandwidth = BandwidthSelect( train );

	//float mse = FLT_MAX;
	float corr = FLT_MIN;
	int best_kernel = -1;
	real_array best_props;

	DenseMatrix superKrr(n1,n1), superKer(n2,n1);
	float superWt = 0;

	// create a placeholder for the weight proportions.
	outWeights.resize( dims + 13 );

	DenseMatrix Krr, Ker;
	RBFKernel_Armadillo kernel( bandwidth );
	int k = 0;
	for ( ; k < dims; ++k )
	{
		// have only one dimension in the column select.
		int_array cols;
		cols.push_back(k);

		Stopwatch sw;
		// compute train-train and eval-train kernels.
		kernel.Compute(train, train, Krr, cols );
		float krr_time = sw.Elapsed();

		sw.Restart();
		kernel.Compute(eval, train, Ker, cols );
		float ker_time = sw.Elapsed();

		sw.Restart();
		real_array props_estimated(noClasses);
		if ( !MMD( dynamic_cast<const DenseMatrix &>(inTrain.Labels()), noClasses, Krr, Ker, props_estimated ) )
			continue;

		float mmd_time = sw.Elapsed();

		float corr_now = Correlation( yte_props, props_estimated );
		if ( corr_now > corr )
		{
			best_kernel = k;
			corr = corr_now;
			best_props = props_estimated;
		}

		if ( corr_now >= kCorrelationThreshold )
		{
			Krr *= corr_now;
			superKrr += Krr;

			Ker *= corr_now;
			superKer += Ker;

			superWt += corr_now;

			outWeights[k] = corr_now;
		}

		std::cout << "Dim[" << k << "] CORR=" << corr_now << " {bestCORR=" << corr << "(" << best_kernel << ")}"
					<< "krr: " << krr_time << "mS "
					<< "ker: " << ker_time << "mS "
					<< "mmd: " << mmd_time << "mS "
					<< std::endl;
	}

	for ( int i = -6; i <= 6; ++i, ++k )
	{
		float bw = pow(2,i) * bandwidth * dims * dims;
		RBFKernel_Armadillo kernel( bw );

		// compute train-train and eval-train kernels.
		Stopwatch sw;
		kernel.Compute(train, train, Krr );
		float krr_time = sw.Elapsed();

		sw.Restart();
		kernel.Compute(eval, train, Ker );
		float ker_time = sw.Elapsed();

		sw.Restart();
		real_array props_estimated;
		if ( !MMD( dynamic_cast<const DenseMatrix &>(inTrain.Labels()), noClasses, Krr, Ker, props_estimated ) )
			continue;

		float mmd_time = sw.Elapsed();

		float mse_now = Correlation( yte_props, props_estimated );
		//if ( mse_now < mse )
		if ( mse_now > corr )
		{
			best_kernel = k;
			corr = mse_now;
			best_props = props_estimated;
		}

		if (mse_now >= kCorrelationThreshold)
		{
			Krr *= mse_now;
			superKrr += Krr;

			Ker *= mse_now;
			superKer += Ker;

			superWt = mse_now;

			outWeights[k] = mse_now;
		}

		std::cout << "Multi[" << k << "] CORR=" << mse_now << " {bestCORR=" << corr << "(" << best_kernel << ")}"
					<< "krr: " << krr_time << "mS "
					<< "ker: " << ker_time << "mS "
					<< "mmd: " << mmd_time << "mS "
					<< std::endl;
	}

	std::cout << "Best Theta:\n" << best_props << std::endl;
	std::cout << "L2 norm: " << LpNorm( best_props, yte_props ) << std::endl;

	superKrr *= (1.0/superWt);
	superKer *= (1.0/superWt);

	float super_correlation = -1;
	real_array props_estimated;
	if ( MMD( dynamic_cast<const DenseMatrix &>(inTrain.Labels()), noClasses, superKrr, superKer, props_estimated ))
	{
		std::cout << "Super Theta:\n" << props_estimated << std::endl;

		super_correlation = Correlation( props_estimated, yte_props );
		std::cout << "super correlation: " << super_correlation << std::endl;
		std::cout << "L2 norm: " << LpNorm( props_estimated, yte_props ) << std::endl;

		// super kernel didn't contribute, so use the best kernel with binary weights.
		if ( super_correlation < corr )
		{
			outWeights.clear();
			outWeights.resize( dims + 13 );
			outWeights[best_kernel] = 1;
		}
	}
	else // super kernel failed, so use the best kernel with binary weights.
	{
		outWeights.clear();
		outWeights.resize( dims + 13 );
		outWeights[best_kernel] = 1;
	}

}

void
ClassRatioEstimator::GetKernels( const Matrix &inA, const Matrix &inB, DenseMatrix &outKernel, float inBandwidth, const real_array &inWts )
{
	int dimensions = inA.Columns();

	real_array bandwidths;
	for (int i = -6; i <= 6; ++i )
	{
		float product = pow(2,i);
		product *= inBandwidth * dimensions * dimensions;
		bandwidths.push_back( product );
	}

	float totalWt = 0;
	outKernel.Resize(inA.Rows(), inB.Rows());

	int univariateGaussians = dimensions;
	RBFKernel_Armadillo kernel( inBandwidth );
	for ( int k = 0; k < dimensions; ++k )
	{
		// skip kernels that are not required.
		if ( inWts[k] == 0 )
			continue;

		// have only one dimension in the column select.
		int_array cols;
		cols.push_back(k);

		std::cerr << "Dim[" << k+1 << "]: ";
		Stopwatch sw;

		DenseMatrix K;
		// kernel computed on a per dimension basis.
		kernel.Compute( inA, inB, K, cols );
		K *= inWts[k];
		totalWt += inWts[k];
		outKernel += K;

		std::cerr << sw.Elapsed() << " mS" << std::endl;
	}

	int nofKernels = univariateGaussians + bandwidths.size();
	for ( int k = univariateGaussians; k < nofKernels; ++k )
	{
		if ( inWts[k] == 0 )
			continue;

		float bw = bandwidths[ k-univariateGaussians ];
		RBFKernel_Armadillo kernel(bw);

		std::cerr << "BW[" << k+1-univariateGaussians << "]: ";
		Stopwatch sw;

		DenseMatrix K;
		kernel.Compute( inA, inB, K );
		K *= inWts[k];
		totalWt += inWts[k];
		outKernel += K;

		std::cerr << sw.Elapsed() << " mS" << std::endl;
	}

	outKernel *= (1.0/totalWt);
}

void ClassRatioEstimator::GetKernels(const Matrix& inA, const Matrix& inB, dense_matrix_array &outKernels, float inBandwidth, bool inMulti, KernelImplType inType )
{
	int dimensions = inA.Columns();

	real_array bandwidths;
	for (int i = -6; i <= 6; ++i )
	{
		float product = pow(2,i);
		product *= inBandwidth * dimensions * dimensions;
		bandwidths.push_back( product );
	}

	int univariateGaussians = dimensions;
	if ( inMulti )
		univariateGaussians = 0;
	else
	{
		std::auto_ptr<Kernel> kernel;
		if ( inType == eNAIVE_THREADED )
			kernel.reset( new RBFKernel_T( inBandwidth) );
		else if ( inType == eARMADILLO )
			kernel.reset( new RBFKernel_Armadillo( inBandwidth ) );
		else
			kernel.reset( new RBFKernel( inBandwidth ) );

		outKernels.resize( dimensions );
		for ( int k = 0; k < dimensions; ++k )
		{
			// have only one dimension in the column select.
			int_array cols;
			cols.push_back(k);

			std::cerr << "Dim[" << k+1 << "]: ";
			Stopwatch sw;
			// kernel computed on a per dimension basis.
			kernel->Compute( inA, inB, outKernels[k], cols );
			std::cerr << sw.Elapsed() << " mS" << std::endl;
		}

	}

	int nofKernels = univariateGaussians + bandwidths.size();
	outKernels.resize( nofKernels );
	for ( int k = univariateGaussians; k < nofKernels; ++k )
	{
		float bw = bandwidths[ k-univariateGaussians ];
		std::auto_ptr<Kernel> kernel;
		if ( inType == eNAIVE_THREADED )
			kernel.reset( new RBFKernel_T( inBandwidth) );
		else if ( inType == eARMADILLO )
			kernel.reset( new RBFKernel_Armadillo( inBandwidth ) );
		else
			kernel.reset( new RBFKernel( inBandwidth ) );

		std::cerr << "BW[" << k+1-univariateGaussians << "]: ";
		Stopwatch sw;
		kernel->Compute( inA, inB, outKernels[k] );
		std::cerr << sw.Elapsed() << " mS" << std::endl;
	}
}

/**
 * function [theta, obj] = MMD(Y, c, Krr, Ker)

	H = zeros(c);
	f = zeros(c, 1);
	for i = 1:c
		idx1 = Y == i;
		for j = 1:c
			idx2 = Y == j;
	%         if i == j
	%             Ktemp = Krr(idx1, idx2);
	%             H(i, j) = 2*(sum(sum((1 - eye(size(Ktemp))) .* Ktemp)) / (size(Ktemp, 1) * (size(Ktemp, 1) - 1)));
	%         else
				H(i, j) = 2*mean(mean(Krr(idx1, idx2)));
	%         end
		end
		f(i) = -2 * mean(mean(Ker(:, idx1)));
	end

	H = 0.5*(H + H');
	A = [];
	b = [];
	Aeq = ones(1, c);
	beq = 1;
	lb = zeros(c, 1);
	ub = ones(c, 1);
	theta0 = ones(1, c) / c;

	options = optimset('Algorithm', 'active-set', 'Display', 'Off', 'LargeScale', 'Off');

	theta = quadprog(H,f,A,b,Aeq,beq,lb,ub,theta0,options);
	theta = theta./sum(theta);

	obj = .5 * (theta'*H*theta) + theta'*f;
*/

bool ClassRatioEstimator::MMD(const DenseMatrix &inY_, int inClasses, const DenseMatrix& inKrr, const DenseMatrix& inKre, real_array &outValues)
{
	int N = inY_.Rows();
	int_array inY(N);
	for ( int i = 0; i < N; ++i )
		inY[i] = inY_(i,0);

	DenseMatrix H( inClasses, inClasses );
	double_array f( inClasses );

	for ( int i = 0; i < inClasses; ++i )
	{
		int_array idx1 =  Indices( inY, i+1 );
		int size1 = idx1.size();

		for ( int j = 0; j < inClasses; ++j )
		{
			int_array idx2 = Indices( inY, j+1 );
			int size2 = idx2.size();
			DenseMatrix ktemp = inKrr.Select(idx1, idx2);
			/*
			if ( i == j )
			{
				// H(i, j) = 2*(sum(sum( (1 - eye(size(Ktemp))) .* Ktemp)) / (size(Ktemp, 1) * (size(Ktemp, 1) - 1)));

				// 1 - eye(size(Ktemp)) := -1 * (eye(size(Ktemp))-1)
				IdentityMatrix eye( size1, size2 );
				eye -= 1;
				eye *= -1;

				eye *= ktemp;
				float sum = eye.Sum(DenseMatrix::eColWise).Sum(DenseMatrix::eRowWise)(0,0);
				float denom = (size1 * (size1 - 1.0));

				H(i, j) = 2.0 * sum / denom;
			}
			else */
			{
				H(i,j) = ktemp.Mean(DenseMatrix::eColWise).Mean(DenseMatrix::eRowWise)(0,0) * 2.0;
			}
		}

		int_array dummy;
		DenseMatrix ktemp = inKre.Select(dummy, idx1);
		f[i] = -2.0 * ktemp.Mean(DenseMatrix::eColWise).Mean(DenseMatrix::eRowWise)(0,0);
	}

	H += H.Transpose();
	H *= 0.5;

	Qdata q(H);
	int result = QuadProg( q, &f[0], inClasses, outValues );

/*
 * @NOTE: http://in.mathworks.com/matlabcentral/fileexchange/35938-converts-a-non-positive-definite-symmetric-matrix-to-positive-definite-symmetric-matrix/content/topdm.m

	if ( result )
	{
		using namespace arma;
		std::cerr << "Converting Objective Matrix to PSD!..";

		mat qq(inClasses, inClasses);
		for ( int j = 0; j < inClasses; ++j )
			for ( int i = 0; i < inClasses; ++i )
				qq(i,j) = H(i,j);

		vec eigval;
		mat eigvec;

		eig_sym(eigval, eigvec, qq);

		for ( int i = 0; i < eigval.n_elem; ++i )
		{
			std::cerr << "eigen->" << i << ": " << eigval(i) << std::endl;
			if ( eigval(i) < 10E-10 )
				eigval(i) = 10E-6;
		}

		mat qq_psd = eigvec*diagmat(eigval)*eigvec.t();
		Qdata q1(qq_psd);
		result = QuadProg( q1, &f[0], inClasses, outValues );

		if ( result )
			std::cerr << "FAILED" << std::endl;
		else
			std::cerr << "WORKED!!" << std::endl;
	}
*/
	return result == 0;
}

